client_config_backend: settings
client_config:
  client_id: CLIENT_SECRETS['web']['client_id']
  client_secret: CLIENT_SECRETS['web']['client_secret']
  auth_uri: 'https://accounts.google.com/o/oauth2/auth'
  token_uri: 'https://oauth2.googleapis.com/token'
  redirect_uris: CLIENT_SECRETS['web']['redirect_uris']
  revoke_uri: 'https://accounts.google.com/o/oauth2/revoke'
  auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs'

save_credentials: False

oauth_scope:
  - https://www.googleapis.com/auth/drive



  